# Generated by Django 5.2.1 on 2025-06-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootZonePlusApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.categorie_equipe'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='pays_origine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.pays'),
        ),
    ]
