# Generated by Django 5.2.1 on 2025-06-11 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootZonePlusApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.continent'),
        ),
    ]
