# Generated by Django 5.2.1 on 2025-06-01 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootZonePlusApp', '0002_equipe_categorie_equipe_pays_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='reservation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.reservation'),
        ),
        migrations.AddField(
            model_name='place',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.match'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.match'),
        ),
        migrations.AddField(
            model_name='stade',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.pays'),
        ),
        migrations.CreateModel(
            name='PlaceReservee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.place')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='FootZonePlusApp.reservation')),
            ],
        ),
    ]
