# Generated by Django 5.2.1 on 2025-06-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootZonePlusApp', '0003_paiement_reservation_place_match_reservation_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.categorie_match'),
        ),
        migrations.AddField(
            model_name='match',
            name='equipe_locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.equipe'),
        ),
        migrations.AddField(
            model_name='match',
            name='stade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.stade'),
        ),
    ]
