# Generated by Django 5.2.1 on 2025-06-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootZonePlusApp', '0004_match_categorie_match_equipe_locale_match_stade'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.continent'),
        ),
    ]
