# Generated by Django 5.2.3 on 2025-06-15 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootZonePlusApp', '0002_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipelocale',
            name='nom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.equipe'),
        ),
        migrations.AlterField(
            model_name='equipevisiteuse',
            name='nom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.equipe'),
        ),
    ]
