# Generated by Django 5.2.1 on 2025-06-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootZonePlusApp', '0002_pays_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
