# Generated by Django 5.2.1 on 2025-06-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootZonePlusApp', '0003_match_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
