# Generated by Django 5.2.3 on 2025-06-15 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootZonePlusApp', '0003_alter_equipelocale_nom_alter_equipevisiteuse_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='equipe_locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.equipelocale'),
        ),
        migrations.AlterField(
            model_name='match',
            name='equipe_visiteuse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.equipevisiteuse'),
        ),
    ]
