# Generated by Django 5.2.3 on 2025-06-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootZonePlusApp', '0004_alter_match_equipe_locale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='date_heure',
            new_name='heure',
        ),
        migrations.RemoveField(
            model_name='match',
            name='date_time_add',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
