# Generated by Django 5.2.1 on 2025-06-12 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootZonePlusApp', '0004_alter_match_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipevisiteuse',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='match',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='pays',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='match',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='pays_origine',
        ),
        migrations.AlterField(
            model_name='match',
            name='equipe_locale',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='equipevisiteuse',
            name='pays_origine',
        ),
        migrations.AlterField(
            model_name='match',
            name='equipe_visiteuse',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='match',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='stade',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='stade',
        ),
        migrations.RemoveField(
            model_name='match',
            name='stade',
        ),
        migrations.RemoveField(
            model_name='match',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='place',
        ),
        migrations.AddField(
            model_name='match',
            name='lieu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date_heure',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Ouvert', 'Ouvert'), ('Fermé', 'Fermé')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='numéro',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='rangée',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PlaceReservee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.place')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FootZonePlusApp.reservation')),
            ],
        ),
        migrations.DeleteModel(
            name='Categorie_Equipe',
        ),
        migrations.DeleteModel(
            name='Categorie_Match',
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='Equipe',
        ),
        migrations.DeleteModel(
            name='EquipeVisiteuse',
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
        migrations.DeleteModel(
            name='Pays',
        ),
        migrations.DeleteModel(
            name='Stade',
        ),
    ]
