# Generated by Django 5.2.3 on 2025-06-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FootZonePlusApp', '0005_rename_date_heure_match_heure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='lieu',
        ),
    ]
