# Generated by Django 5.2.3 on 2025-06-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootZonePlusApp', '0007_reservation_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('Validé', 'Validé'), ('En cours', 'En cours'), ('En attente', 'En attente')], max_length=20, null=True),
        ),
    ]
